export const listaSoftware = {
  AT1_4_5: [
    "PSEINT",
    "CODEBLOCKS",
    "Cisco Packet Tracer 8.2",
    "Apache Netbeans 20",
    "Java JDK 8",
    "Java JDK 11",
    "Java JDK 21",
    "MySQL Community Server 8.0.30",
    "Microsoft Visual Studio 2022 Community",
    "Microsoft SQL Server Developer",
    "Bizagi Modeler",
    "Pencil Project",
    "OracleXE",
    "Oracle SQL Developer",
    "Prolog",
    "Visual Studio Code",
    "Intellij Idea",
    "Android Studio Hedgehog 2023.1.1",
    "Arduino",
    "Geogebra",
    "JFLAP",
    "VirtualBox 7.0",
    "Microsoft Project",
    "Star UML",
    "XAMPP",
    "PostgreSQL 16",
    "Microsoft Office",
    "Internet",
  ],
  AT3: [
    "COMPAQ",
    "Microsoft Office",
    "Internet",
    "minitab 17",
  ],
  AT2: [
    "Ansys",
    "AutoCAD",
    "Arduino",
    "CODEBLOCKS",
    "Java",
    "LabView",
    "Microsoft Office",
    "Octave GNU",
    "Vivado",
    "SolidWorks",
  ],
};
